import os
from pathlib import Path

API_ROOT = Path(__file__).resolve().parent.parent
DATABASE_PATH = Path(
    os.getenv("NEXUS_DATABASE_PATH", API_ROOT / "nexus_observatory.db")
)
OPENAI_COMPATIBLE_BASE_URL = os.getenv("OPENAI_COMPATIBLE_BASE_URL")
OPENAI_COMPATIBLE_API_KEY = os.getenv("OPENAI_COMPATIBLE_API_KEY")
OPENAI_COMPATIBLE_DEFAULT_MODEL = os.getenv("OPENAI_COMPATIBLE_DEFAULT_MODEL")
CUSTOM_ENDPOINT_BASE_URL = (
    os.getenv("CUSTOM_ENDPOINT_BASE_URL") or OPENAI_COMPATIBLE_BASE_URL
)
CUSTOM_ENDPOINT_API_KEY = (
    os.getenv("CUSTOM_ENDPOINT_API_KEY") or OPENAI_COMPATIBLE_API_KEY
)
CUSTOM_ENDPOINT_DEFAULT_MODEL = os.getenv(
    "CUSTOM_ENDPOINT_DEFAULT_MODEL",
) or OPENAI_COMPATIBLE_DEFAULT_MODEL
